[tool.poetry]
name = "web-hw-02"
version = "0.1.0"
description = ""
authors = ["Katana-devel <egorpilipenko0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
